version: '3'

services:
  fastapi_mongo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/fastapi_mongo
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi_mongo

volumes:
  mongodb_data: